# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('cmsplugin_slick', '0002_carousel_default_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caroselimagefolder',
            options={'verbose_name': 'Carousel Image Folder', 'verbose_name_plural': 'Image Folder Carousels'},
        ),
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': 'Carousel', 'verbose_name_plural': 'Carousels'},
        ),
        migrations.AlterModelOptions(
            name='carouselbreakpoint',
            options={'verbose_name': 'Carousel Breakpoint', 'verbose_name_plural': 'Carousel Breakpoints'},
        ),
        migrations.AlterModelOptions(
            name='carouselelementwrapper',
            options={'verbose_name': 'Carousel Slide', 'verbose_name_plural': 'Carousel Slides'},
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='crop',
            field=models.BooleanField(default=True, verbose_name='crop'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='style',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Style'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='thumbnail_option',
            field=models.ForeignKey(blank=True, help_text='overrides width, height, crop and upscale with values from the selected thumbnail option', null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.ThumbnailOption', verbose_name='thumbnail option'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='upscale',
            field=models.BooleanField(default=True, verbose_name='upscale'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='use_autoscale',
            field=models.BooleanField(default=False, help_text='tries to auto scale the image based on the placeholder context', verbose_name='use automatic scaling'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='use_original_image',
            field=models.BooleanField(default=False, help_text='do not resize the image. use the original image instead.', verbose_name='use the original image'),
        ),
        migrations.AddField(
            model_name='caroselimagefolder',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='width'),
        ),
        migrations.AlterField(
            model_name='caroselimagefolder',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_caroselimagefolder', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_carousel', serialize=False, to='cms.CMSPlugin'),
        ),
        migrations.AlterField(
            model_name='carouselelementwrapper',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='cmsplugin_slick_carouselelementwrapper', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
