# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_slick', '0003_auto_20170429_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='auto_breakpoints',
            field=models.BooleanField(default=True, verbose_name='Auto Breakpoints'),
        ),
        migrations.AddField(
            model_name='carousel',
            name='mobile_first',
            field=models.BooleanField(default=False, help_text='Responsive settings use mobile first calculation', verbose_name='Mobile First'),
        ),
    ]
